[[pages]]
# 首页
path = "pages/index/index"
config = { defaultTitle = "" }

[[pages]]
# 登录页
path = "pages/login/login"
config = { pullRefresh = false, defaultTitle = "登录" }

[[subPackages]]
root = 'mine'

[[subPackages.pages]]
path = "cancleuser/index"
config = { navigationBarTextStyle = "black", navigationBarBackgroundColor = "#FFF", backgroundTextStyle = "dark", defaultTitle = "注销帐号" }


[tabBar]
textColor = "#9595BD"

[[items]]
pagePath = "pages/index/index"
name = "首页"
